### PR TITLE
Dwc checklist

### PR DESCRIPTION
**Pull request by LienReyserhove**
Behold the new DwC checklist. This is a first version, thus open to suggestions and adaptations. Below, I gave an overview of all files, with their respective DwC terms (or changes in case of the `raw file`). I commented on these terms when in doubt, suggestions and changes are more than welcome. Please check off the changes/DwC terms when they are reviewed and considered OK

## raw file

[File](http://www.aquaticinvasions.net/2016/Supplements/AI_2016_Boets_etal_Supplement.xls) was adapted to make further processing easier:

- [x] adding "ID" for later mapping to `taxonID`. We decided that `taxonID`should contain the shortname of the DwC Archive in GBIF (here: alien-macroinvertebrates-checklist) followed by ":taxon" and a unique number.
- [x] small changes in `origin` to avoid confusion in R between "-" as a separator between regions and "-" as part of the region name.  

## Taxon

* [x] language
* [x] license
* [x] rightsHolder
* [x] accessRights
* [ ] datasetID: to be completed after publication
* [x] datasetName: `Checklist of alien macroinvertebrates in Flanders, Belgium`
* [x] references: now referenced to supplementary information of Boets et al. 2016, not sure if this is correct **remove**
* [x] taxonID: format `alien-macroinvertebrates-checklist:taxon:1`
* [x] scientificName: is unique
* [x] kingdom
* [x] phylum: in R correct `Crustacea` to `Arthropoda`
* [x] order: not recognized as order: `Tubficida`, probably good to verify others as well. **trim names**
* [x] family: seems OK
* [x] taxonRank: should be `subspecies` for Dreissena rostriformis bugensis
* [x] scientificNameAuthorship: we don't have this no information **remove**
* [x] nomenclaturalCode

## Distribution

* [x] taxonID
* [x] locationID
* [x] locality
* [x] countryCode
* [x] occurrenceStatus: `present` (lowercase)
* [x] eventDate: use `/` to separate years
* [x] source: extra recode(), see comment below

---

Actions taken:

* format `eventDate`: `start_year`- `current_year` (yyyy-yyyy).
* `start_year` (yyyy) contains the information from the following formats in `raw_first_occurrence_in_flanders`: "yyyy", "< yyyy", "<yyyy" and "before yyyy" OR the first year of the interval "yyyy-yyyy"
* `current_year` (yyyy) will contain the current year OR the last year of the interval "yyyy-yyyy":
* source: now copied. But:
    * is this the correct DwC term for this information anyway? --> possibility to use "refernce extension?" **Is perfect field for this info**
    * What with reference "This study" --> change to Boets et al. 2016? **yes please**
    * supplement with more information such as journal and title? Without this information, it is difficult to track the right article (e.g. Sablon et al. 2010a and Sablon et al. 2010b) **see comment below**

## Description

* [x] taxonID
* [x] description: extra recode(), see comment below
* [x] type: native range, pathway and habitat (comment: see below)
* [x] source: extra recode(), see comment below
* [x] language

Specifications for `type`:

### native range:

* approach comparable to alien_plants
* recoding of world regions according to [UN standard area code](https://unstats.un.org/unsd/methodology/m49/) 

### pathway

* The content in type `pathway` was now copied and cleaned from `pathway_of_introduction` in the raw data file. However see #19 and #23

## salinity zone

* I took into account the suggestions by @timadriaens  to put the information on salinity zone in `habitat`, rather than creating a type `salinity zone`. This appeared more evident to me, but I'm open to other suggestions. **good**
* abbreviations `B`, `M` and `F` were substituted by `brackish`, `marine` and `freshwater` respectively.

### CODE REVIEW

**Review by peterdesmet — CHANGES_REQUESTED** [review]
Feedback:

* Nice work!
* Updated todo list in body of this pull request.
* `reference` = for that individual taxon, so wouldn't use that for whole Excel file.

Questions:

* According to which documentation is `scientificNameAuthorship` mandatory?
* Yes, sources might be difficult to track down with the current info. Are those sources listed in the Boets et al.?

Extra recode for native range, based on Wikipedia entries I could find (so commonly used), are sometimes in contrast with https://unstats.un.org/unsd/methodology/m49/ so not sure.

* Eastern Asia -> [East Asia](https://en.wikipedia.org/wiki/East_Asia) (is in contrast with https://unstats.un.org/unsd/methodology/m49/ though)
* Indio-Pacific -> [Indo-Pacific](https://en.wikipedia.org/wiki/Indo-Pacific)
* North-eastern Asia -> [Northeast Asia](https://en.wikipedia.org/wiki/Northeast_Asia)
* South-eastern Asia -> [Southeast Asia](https://en.wikipedia.org/wiki/Southeast_Asia) (is in contrast with https://unstats.un.org/unsd/methodology/m49/ though)
* USA -> United States
* West-Atlantic -> Western Atlantic (West-Atlantic = airline company)
* Western Africa -> [West Africa](https://en.wikipedia.org/wiki/West_Africa) (is in contrast with https://unstats.un.org/unsd/methodology/m49/ though)

Extre recode() for source:

* Nyst 1835; Adam 1947 -> Nyst 1835 | Adam 1947
* This study -> Boets et al. 2016
* Faasse and Van Moorsel, 2003 -> remove comma from source file

**Comment by peterdesmet** [comment]
I've also added specifications based on everything discussed here: 22327ba38325bf15cd425a106205f5490e04aa51

**Comment by LienReyserhove** [comment]
I updated the dwc_checklist mapping according to the suggestions by @peterdesmet 

### Taxon:
* **references**: removed
* **phylum**: Crustacea changed to Arthropoda
* **order**: 
	- Tubficida --> should this be Tubificidae? This is a suborder. The order is "Haplotaxida";  
	- Veneroidea --> This is a superfamily. The order is "Venerida"
	- Caution, according to [WoRMS](http://www.marinespecies.org/):
		- Euheterodonta --> [unassigned, temporary name]
		- Pulmonata --> [unassigned, temporary name]
* **taxonRank**: changed "species" to "subspecies" for Dreissena rostriformis bugensis

### Distribution:

* **occurrenceStatus**: changed to "present" (lowercase)
* **eventDate**: "/"  to separate dates)
* **source**: Most references can be found in the reference list of Boets et al. 2016. The question is whether this information should be integrated in the checklist. In my opinion, this would make it easier to track the necessary information in the checklist (i.e. this would make the checklist more independent of the research article), which is a good thing (but more work :-) ). **However**:
	- Reference unclear or not in Boets et al. 2016:
		- `Collection RBINS`
		- `Dumoulin 2004`
		- `Boets et al. unpub data`
	- Adaptations (recode)
		- `Van  Haaren and Soors 2009`   --> lower case for "Van" and remove extra space
		- `Adam and Leloup 1934`   --> remove extra space     
		- `Faasse and Van Moorsel, 2003`" --> remove comma
		- `This study` --> Change to `Boets et al. 2016`
		- `Nyst 1835; Adam 1947` -->  `Nyst 1835 | Adam 1947`

### Descritpion:

* **description**: I'm still more fond of the [UNstats defenition](https://unstats.un.org/unsd/methodology/m49/), as this seems more official to me than a Wikipedia page. However, if it is common practice to use Wikipedia terminology, I will change this. 
I agree that an airline company does not belong in description, that USA should be United States of America and I corrected the typo in "Indio-Pacific"

### Answer to Question by @peterdesmet :

According to which documentation is scientificNameAuthorship mandatory? 
--> according to the spreadsheet [Open biodiversity data publication via the IPT by INBO](https://docs.google.com/spreadsheets/d/13qSyBS7mZPYENHjPpgEAJirQ58G3pI9tmtW6gvv2vKk/edit#gid=250319423) --> probably wrong... 

Yes, sources might be difficult to track down with the current info. Are those sources listed in the Boets et al.?  --> yes, most of them, see disussion under `source`

**Comment by peterdesmet** [comment]
Nice. Almost there.

* Agree to keep UNstats
* Trim values in `order`: some contain spaces. **TODO**
* Match sources with https://github.com/trias-project/alien-macroinvertebrates/blob/dwc_checklist/data/raw/sources.tsv **TODO** If empty, use original value (like `Collection RBINS`).

**Comment by LienReyserhove** [comment]
adaptations were integrated as requested, i.e.:

* Trim `order`
* Match `sources`

**Comment by peterdesmet** [comment]
Some of the sources are empty now: original value should be maintained if no `reference` is found.

**Comment by LienReyserhove** [comment]
I updated the script and .csv files with the original values for source when the full reference is absent

**Review by peterdesmet — APPROVED** [review]

**Comment by LienReyserhove** [comment]
Some changes were made according to the suggestions of Pieter Boets, see #28

**Pull request merged**
