### PR TITLE
new dwc_occurrence mapping Part1

### PR DESCRIPTION
**Pull request by LienReyserhove**
This pull request contains several (major) changes to the `dwc_occurrence` mapping.
This is because we decided to go back one step and to extract the raw columns in SSMS to generate the new [denormalized_observations.csv](https://github.com/trias-project/alien-macroinvertebrates/blob/master/data/raw/denormalized_observations.csv) (see #17 ).
 
As a consequence, we had to:
- remove the old dwc_occurrence.R and dwc_occurrence.md files and rewrite the script. 
- carry out the mapping to DwC terms in R instead of in SQL.

Information to perform the mapping was extracted from SSMS and took into account the suggestions from #18 

- [x] type
- [x] language
- [x] license: `http://creativecommons.org/publicdomain/zero/1.0/`
- [x] rightsHolder: `Ghent University Aquatic Ecology`
- [x] accessRights
- [x] datasetID: updated to https://doi.org/10.15468/xjtfoo
- [x] institutionCode: updated
- [x] datasetName: updated to `Alien macroinvertebrates in Flanders, Belgium` (was `macro-invertebrates` before)
- [x] basisOfRecord
- [x] occurrenceID
- [x] recordedBy: Van de Neucker T → Van den Neucker T, rest ok
- [x] otherCatalogNumbers
- [x] eventDate: use startDate
- [x] verbatimEventDate: populate for ranges only
- [x] continent
- [x] countryCode 
- [x] municipality: not a vocabulary --> contains codes (e.g. "ES75D") --> remove these to verbatimLocality? **not worth it**
- [x] verbatimLocality: contains `NULL`. Translate all `NULL` to `NA` when reading dataset in R
- [x] decimalLatitude:change comma to point and rounded
- [x] decimalLongitude:change comma to point and rounded
- [x] geodeticDatum
- [x] coordinateUncertaintyInMeters: always `30` (assumed GPS for all)
- [x] verbatimCoordinates: remove
- [x] verbatimLatitude: see comment below
- [x] verbatimLongitude: see comment below
- [x] verbatimCoordinateSystem: `decimal degrees` or `Belgian Lambert 72`
- [x] verbatimSRS: `WGS84` or `Belgian Datum 1972`
- [x] identifiedBy: Van de Neucker T → Van den Neucker T, rest ok
- [x] scientificName: Dreissena (Dreissena) polymorpha was changed to Dreissena polymorpha 
- [x] kingdom
- [x] taxonRank: changed from "Spp" and "SubSpp"
- [x] scientificNameAuthorship: = from raw data, looks more or less OK
- [x] nomenclaturalCode

### CODE REVIEW

**Review by DimEvil — COMMENTED** [review]
RightsHolder: Ugent: Aquatic Ecology --> We choose this in the time of publication, we keep the value or maybe change to: Ghent University Aquatic Ecology 

Typo you discovered
"Rik Clicque" = "Clique R",  --> "Cliqcue R"

eventDate, not sure if GBIF can handle the / already, suggest to keep startDate in eventDate en place the dateRange in verbatimEventDate

verbatimCoordinatesystem is not decimal degrees (lambert coordinates and some decimal degrees if I remember correctly) Lambert 72 I think

**Comment by peterdesmet** [comment]
How to map the verbatim coordinate information: use `sample_spatial_ref_system` to differentiate and do:

## 166956.8952,214232.8477 (`BD72 `)

* verbatimLatitude: 214233
* verbatimLongitude: 166957
* verbatimCoordinateSystem: Belgium Lambert 72
* verbatimSRS: Belgian Datum 1972

## 51.12857222N,4.35763056E (`LTLN`)

* verbatimLatitude: 51.12857222N
* verbatimLongitude: 4.35763056E
* verbatimCoordinateSystem: decimal degrees
* verbatimSRS: WGS84

**Review by peterdesmet — CHANGES_REQUESTED** [review]
See todo list in PR body

**Comment by LienReyserhove** [comment]
I integrated all earlier comments in the new dwc_occurrence mapping. Please check off in earlier PR body when considered OK

* license: `http://creativecommons.org/publicdomain/zero/1.0/`
* rightsHolder: `Ghent University Aquatic Ecology`
* recordedBy: Van de Neucker T → Van den Neucker T
* eventDate, not sure if GBIF can handle the "/" already: eventDate and verbatimEventDate were adapted:
-  eventDate = start date
-  verbatimEventdate = interval when start date != end date
- verbatimEventdate = empty when start date == end date
* verbatimLocality: all `NULL` translated to `NA` when reading dataset in R
* coordinateUncertaintyInMeters: always `30` (assumed GPS for all)
* verbatimCoordinates: removed and changed to verbatimLatitude and verbatimLongitude
* verbatimLatitude: corrected, based on comments given in "How to map the verbatim coordinate information"
* verbatimLongitude: corrected, based on comments given in "How to map the verbatim coordinate information"
* verbatimCoordinateSystem: `decimal degrees` or `Belgian Lambert 72`
* verbatimSRS: `WGS84` or `Belgian Datum 1972`
* identifiedBy: Van de Neucker T → Van den Neucker T; Rik Clicque" = "Clique R", --> "Cliqcue R"

**Review by peterdesmet — APPROVED** [review]

**Comment by peterdesmet** [comment]
Verified open items on todo list. Looks all good. 👏 👏 👏

**Pull request merged**
